version: '2'
services:
  products:
    image: bifrostuzh/microservices-sample-products
    env_file: .env
    depends_on:
      - mongo

  search:
    image: bifrostuzh/microservices-sample-search
    env_file: .env
    depends_on:
      - mongo

  auth:
    image: bifrostuzh/microservices-sample-auth
    env_file: .env
    depends_on:
      - mongo

  mongo:
    image: mongo:3.2.1
    volumes:
      - "./data:/data/db"

  prometheus:
    image: bifrostuzh/microservices-sample-prometheus
    expose:
     - "9090"